server:
  port: ${PORT:8864}
message: Congifuracion de Producto en el servidor levantado
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8860
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
